version: '3.9'

services:
  app:
    build: .
    container_name: fastapi_app
    volumes:
      - .:/app
      - ./logs:/app/logs  # Adiciona este volume para acessar os logs
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
